berylium/about/urls.py
from django.urls import path
from about import views

app_name = "about"

urlpatterns = [
    path("", views.about, name="about")
]   

berylium/berylium/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('about/', include("about.urls" )),
    path ('services/', include("service.urls")),
    path ('portfolio/', include("works.urls")),
    path ("contacts/", include ("contacts.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

berylium/contacts/urls.py
from django.urls import path
from contacts import views


app_name = "contacts"

urlpatterns = [
    path('', views.contacts, name = "contacts")
]

berylium/main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index')
]

berylium/service/urls.py
from django.urls import path
from service import views

app_name = 'service'

urlpatterns = [
    path ('', views.service, name = 'service')
]

berylium/works/urls.py
from django.urls import path
from works.views import works

app_name = "works"

urlpatterns = [
    path ('', works, name = "works")
]

berylium/about/models.py

from django.db import models


# Create your models here.
class TeamDescription(models.Model):
    text = models.TextField()
    
    def __str__(self):
        return "Team Description"
    
class staff(models.Model):
    name = models.CharField(max_length = 50, blank = False, verbose_name= 'Name')
    post = models.CharField(max_length = 50, blank = False, verbose_name = 'Post at work')
    info = models.CharField(max_length = 250, blank = False, verbose_name = 'employee information')
    image = models.ImageField(upload_to="staff_images", blank=False, unique=True, verbose_name = 'image')
    inst = models.URLField(blank = True, verbose_name = 'instagram') 
    twitter = models.URLField(blank = True, verbose_name = 'twitter')
    facebook = models.URLField(blank = True, verbose_name = 'facebook')

    class Meta:
        db_table = 'staff cards'
        

berylium/contacts/models.py
from django.db import models

# Create your models here.

berylium/main/models.py
from django.db import models

class main(models.Model):
    place_of_interest = models.CharField(max_length = 200, verbose_name = 'place of interest')
    location = models.CharField(max_length = 200, verbose_name = 'location')
    image = models.ImageField(upload_to='place_images',verbose_name="image of the place")

    class Meta:
        db_table = 'pictures on the main page'
        verbose_name = "posts on the main page"

class pic_slider(models.Model):
    image = models.ImageField(upload_to='slider_images')

    class Meta:
        db_table = "images for slider"
        verbose_name = "images for slider"

berylium/service/models.py
from django.db import models

# Create your models here.
class ServicesDescription(models.Model):
    text = models.TextField()

    def __str__(self):
        return 'ServicesDescription'

berylium/works/models.py
from django.db import models

class DescriptionWorks(models.Model):
    text = models.TextField()

    def __str__(self):
        return "DescriptionWorks"

class portfolio(models.Model):
    img = models.ImageField(upload_to="slider_works")
    place_of_interest = models.CharField (max_length = 200, verbose_name = 'place of interest')
    location = models.CharField(max_length = 200, verbose_name = 'location')

    class Meta:
        db_table = "pictures in work page"
        verbose_name = "images for slider"


berylium/about/views.py
from django.shortcuts import render
from about.models import TeamDescription,staff

def about(request):
    team_info =TeamDescription.objects.first()
    staff_info = staff.objects.all()
    return render(request, "about/about.html",{"team_info":team_info, "staff_info":staff_info })

berylium/contacts/views.py
from django.shortcuts import render

# Create your views here.
def contacts(request):
    return render(request, "contacts/contact.html")

berylium/main/views.py
from django.shortcuts import render
from main.models import pic_slider, main

def index(request):
    slides = pic_slider.objects.all()
    pictures = main.objects.all()
    return render(request,"main/index.html",{"slides":slides,'pictures':pictures})

berylium/service/views.py
from django.shortcuts import render
from service.models import ServicesDescription

def service(request):
    info = ServicesDescription.objects.first()
    return render (request, "service/services.html", {'info':info})

berylium/works/views.py
from django.shortcuts import render
from works.models import portfolio,DescriptionWorks


def works(request):

    sliders = portfolio.objects.all()
    info = DescriptionWorks.objects.first()
    return render(request, "works/works.html", {'sliders':sliders, "info":info})

berylium/about/templates/about/about.html
{% extends "main/base/base.html" %}
{% load static %}


		
{% block content %}
		<div class="gtco-section">
			<div class="gtco-container">
				<div class="row gtco-heading">
					<div class="col-md-7 text-left">
						<h2>Our Team</h2>
						<p>{{ team_info.text }}</p>
					</div>
					<div class="col-md-3 col-md-push-2 text-center">
						<p class="mt-md"><a href="#" class="btn btn-special btn-block">Join our team</a></p>
					</div>
				</div>
				<div class="row">

					<div class="col-md-12">
						<div class="owl-carousel owl-carousel-carousel">
						{% for info in staff_info  %}	
							<div class="item">
								<div class="gtco-staff">
									<img src="{{info.image.url}}" alt="" class="img-responsive">
									<h2>{{info.name}}</h2>
									<p class="role">{{info.post}}</p>
									<p>{{info.info}}</p>
									<ul class="fh5co-social">
										<li><a href="{{info.inst}}"><i class="icon-facebook"></i></a></li>
										<li><a href="{{info.twitter}}"><i class="icon-twitter"></i></a></li>
										<li><a href="{{info.instagram}}"><i class="icon-linkedin"></i></a></li>
									</ul>
								</div>
							</div>
						{% endfor %}	
						</div>
					</div>
					
				</div>
			</div>
		</div>
	<!-- END .gtco-services -->
{% endblock  %}	

berylium/contacts/templates/contacts/contact.html
{% extends "main/base/base.html" %}
{% load static %}
{% block content %}
		<div class="gtco-section">
			<div class="gtco-container">
				<div class="row gtco-heading">
					<div class="col-md-7 text-left">
						<h2>Contact</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.</p>
					</div>
					<div class="col-md-3 col-md-push-2 text-center">
						<p class="mt-md"><a href="#" class="btn btn-special btn-block">Contact us</a></p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<form action="#">
							<div class="form-group">
								<label for="name">Name</label>
								<input type="text" class="form-control" id="name">
							</div>
							<div class="form-group">
								<label for="name">Email</label>
								<input type="text" class="form-control" id="email">
							</div>
							<div class="form-group">
								<label for="message"></label>
								<textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
							</div>
							<div class="form-group">
								<input type="submit" class="btn btn btn-special" value="Send Message">
							</div>
						</form>
					</div>
					<div class="col-md-5 col-md-push-1">
						<div class="gtco-contact-info">
							<h3>Our Address</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							<ul >
								<li class="address">198 West 21th Street, Suite 721 New York NY 10016</li>
								<li class="phone"><a href="tel://1234567890">1235 2355 980</a></li>
								<li class="email"><a href="#">info@yoursite.com</a></li>
								<li class="url"><a href="#">www.yoursite.com</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END Contact -->

		<div id="map"></div>
	{% endblock  %}

		

	

berylium/main/templates/main/base/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Aesthetic by freehtml5.co
	Twitter: http://twitter.com/fh5co
	URL: http://freehtml5.co
-->
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Beryllium &mdash; Free Website Template, Free HTML5 Template by FreeHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Montserrat:400,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static "css/animate.css" %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static "css/icomoon.css" %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static "css/themify-icons.css" %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
	<link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static "css/style.css" %}">

	<!-- Modernizr JS -->
	<script src="{% static "js/modernizr-2.6.2.min.js" %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
		
	<div class="gtco-loader"></div>
	
	<div id="page">

		<nav class="gtco-nav" role="navigation">
			<div class="gtco-container">
				
				<div class="row">
					<div class="col-sm-2 col-xs-12">
						<div id="gtco-logo"><a href="{% url "main:index" %}">Beryllium</div>
					</div>
					<div class="col-xs-10 text-right menu-1">
						<ul>
							<li class="active"><a href="{% url "main:index" %}">Home</a></li>
							<li><a href="{% url "about:about" %}">About</a></li>
							<li class="has-dropdown">
								<a href="{% url "service:service" %}">Services</a>
								<ul class="dropdown">
									<li><a href="#">Web Design</a></li>
									<li><a href="#">eCommerce</a></li>
									<li><a href="#">Branding</a></li>
									<li><a href="#">API</a></li>
								</ul>
							</li>
							<li class="has-dropdown">
								<a href="#">Dropdown</a>
								<ul class="dropdown">
									<li><a href="#">HTML5</a></li>
									<li><a href="#">CSS3</a></li>
									<li><a href="#">Sass</a></li>
									<li><a href="#">jQuery</a></li>
								</ul>
							</li>
							<li><a href="{% url "works:works" %}">Portfolio</a></li>
							<li><a href="{% url "contacts:contacts" %}">Contact</aurl></li>
						</ul>
					</div>
				</div>
				
			</div>
		</nav>
		
{% block content %}

{% endblock  %}

		<div class="gtco-section">
			<div class="gtco-container">
				<div class="row">
					<div class="col-md-6 gtco-news">
						<h2>News</h2>	
						<ul>
							<li>
								<a href="#">
									<span class="post-date">September 10, 2016</span>
									<h3>Manila Bridge Re-construction</h3>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod...</p>
								</a>
							</li>

							<li>
								<a href="#">
									<span class="post-date">September 10, 2016</span>
									<h3>Manila Bridge Re-construction</h3>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod...</p>
								</a>
							</li>

							<li>
								<a href="#">
									<span class="post-date">September 10, 2016</span>
									<h3>Manila Bridge Re-construction</h3>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod...</p>
								</a>
							</li>
						</ul>
						<p><a href="#" class="btn btn-sm btn-special">More News</a></p>
					</div>
					<!-- END News -->
					<div class="col-md-5 col-md-push-1 gtco-testimonials">
						<h2>Testimonials</h2>
						<blockquote>
							<p>&ldquo;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.&ldquo;</p>
							<p class="author"><cite>&mdash; John Doe Dueller</cite></p>
						</blockquote>
						<blockquote>
							<p>&ldquo;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.&ldquo;</p>
							<p class="author"><cite>&mdash; John Doe Dueller</cite></p>
						</blockquote>
					</div>
				</div>
			</div>
		</div>
		<!-- END  -->

		<div class="gtco-section gto-features">
			<div class="gtco-container">
				<div class="row">
					<div class="col-md-4">
						<div class="feature-left">
							<i class="ti-zip icon"></i>
							<div class="copy">
								<h3>Architect</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="feature-left">
							<i class="ti-hummer icon"></i>
							<div class="copy">
								<h3>Planning</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="feature-left">
							<i class="ti-plug icon"></i>
							<div class="copy">
								<h3>Parks &amp; Events</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>


		<footer id="gtco-footer" class="gtco-section" role="contentinfo">
			<div class="gtco-container">
				<div class="row row-pb-md">
					<div class="col-md-4 gtco-widget gtco-footer-paragraph">
						<h3>Beryllium</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod.</p>
					</div>
					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6 gtco-footer-link">
								<h3>Links</h3>
								<ul class="gtco-list-link">
									<li><a href="{% url "main:index" %}">Home</a></li>
									<li><a href="#">Features</a></li>
									<li><a href="#">Products</a></li>
									<li><a href="#">Testimonial</a></li>
									<li><a href="#">Contact</a></li>
								</ul>
							</div>
							<div class="col-md-6 gtco-footer-link">
								<h3>Work</h3>
								<ul class="gtco-list-link">
									<li><a href="#">New York Arena</a></li>
									<li><a href="#">Eagle Park</a></li>
									<li><a href="#">Nationals Park</a></li>
									<li><a href="#">Manila Park</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-4 gtco-footer-subscribe">
						<form class="form-inline">
						  <div class="form-group">
						    <label class="sr-only" for="exampleInputEmail3">Email address</label>
						    <input type="email" class="form-control" id="" placeholder="Email">
						  </div>
						  <button type="submit" class="btn btn-primary">Send</button>
						</form>
					</div>
				</div>
			</div>
			<div class="gtco-copyright">
				<div class="gtco-container">
					<div class="row">
						<div class="col-md-6 text-left">
							<p><small>&copy; 2016 Free HTML5. All Rights Reserved. </small></p>
						</div>
						<div class="col-md-6 text-right">
							<p><small>Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://pixeden.com/" target="_blank">Pixeden</a> &amp; <a href="http://unsplash.com" target="_blank">Unsplash</a></small> </p>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- END footer -->

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static "js/jquery.min.js" %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
	<!-- Bootstrap -->
	<script src="{% static "js/bootstrap.min.js" %}"></script>
	<!-- Waypoints -->
	<script src="{% static "js/jquery.waypoints.min.js" %}"></script>
	<!-- Carousel -->
	<script src="{% static "js/owl.carousel.min.js" %}"></script>

	<!-- Main -->
	<script src="{% static "js/main.js" %}"></script>

	</body>
</html>


berylium/main/templates/main/index.html
{% extends "main/base/base.html" %}
{% load static %}

{% block content %}
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="owl-carousel owl-carousel-fullwidth">
						{% for slide in slides %}
							<div class="item">
								<a href="#">
									<img src="{{ slide.image.url }}" alt="Slide Image">
									<div class="slider-copy">
										<h2>{{ slide.title }}</h2>
									</div>
								</a>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>

		<div class="gtco-section">
			<div class="gtco-container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 gtco-heading text-center">
						<h2>Work</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.</p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="owl-carousel owl-carousel-carousel">
							{% for picture in pictures %}
								<div class="item">
									<div class="gtco-item">
										<a href="#"><img src="{{ picture.image.url }}" alt="" class="img-responsive"></a>
										<h2><a href="#">{{ picture.place_of_interest }}</a></h2>
										<p class="role">{{ item.location }}</p>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- END Work -->
{% endblock %}
		

berylium/service/templates/service/services.html
{% extends "main/base/base.html" %}
{% load static %}

	{% block content %}
		<div class="gtco-section gtco-services">
			<div class="gtco-container">
				<div class="row gtco-heading">
					<div class="col-md-7 text-left">
						<h2>Our Services</h2>
						<p>{{info.text}}</p>
					</div>
					<div class="col-md-3 col-md-push-2 text-center">
						<p class="mt-md"><a href="#" class="btn btn-special btn-block">Join our team</a></p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-briefcase icon"></i>
							<div class="copy">
								<h3>Building &amp; Architect</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-package icon"></i>
							<div class="copy">
								<h3>Planning</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					
					<div class="clearfix visible-sm-block"></div>

					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-brush-alt icon"></i>
							<div class="copy">
								<h3>Interior Design</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					
					<div class="clearfix visible-md-block"></div>

					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-home icon"></i>
							<div class="copy">
								<h3>Sustainability</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>

					<div class="clearfix visible-sm-block"></div>

					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-notepad icon"></i>
							<div class="copy">
								<h3>Events</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>


					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="feature-left">
							<i class="ti-plug icon"></i>
							<div class="copy">
								<h3>Bridge</h3>
								<p>Lorem ipsum dolor sit ameteista, consectetur adipiscing is not elitistaris.</p>
								<p><a href="#" class="gtco-more">Learn more</a></p>
							</div>
						</div>
					</div>
					
					

				</div>
			</div>
		</div>
		<!-- Services -->
	{% endblock  %}

berylium/works/templates/works/works.html
{% extends "main/base/base.html" %}
{% load static %}


{% block content %}
		<div class="gtco-section">
			<div class="gtco-container">
				<div class="row gtco-heading">
					<div class="col-md-7 text-left">
						<h2>Works</h2>
						<p>{{info.text}}</p>
					</div>
					<div class="col-md-3 col-md-push-2 text-center">
						<p class="mt-md"><a href="#" class="btn btn-special btn-block">Contact us</a></p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="owl-carousel owl-carousel-carousel">

							{% for slide in sliders %}
								<div class="item">
									<div class="gtco-item">
										<a href="#"><img src="{{slide.img.url}}" alt="" class="img-responsive"></a>
										<h2><a href="#">{{slide.place_of_interest}}</h2></a>
										<p class="role">{{slide.location}}</p>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock %}